[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "8593a0f534bdcd6aedd8f78a8ed34a7695511643"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "792119f13c10b4bacbd88fac700edcc63d6fae3d0f1d2115e2d9a0f175ae78b6"
    url = "https://github.com/maxfadson/libwebsockets_jll.jl/releases/download/4.3.3-bin/libwebsockets.v4.3.3.aarch64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "fa76deb2c508100ecde59904a489f82ce836be93"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "eeb51056ed2d685ed8a6d8fa3d87cef0bc49a153618acbe8e066bccfcfba52d5"
    url = "https://github.com/maxfadson/libwebsockets_jll.jl/releases/download/4.3.3-bin/libwebsockets.v4.3.3.x86_64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "842fb870739950d1ec710fe3640d2adaa771574c"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "96536ed6b260d6ddca44cbb8358deb3a64a3e9463e1218de8c32db26e8480c69"
    url = "https://github.com/maxfadson/libwebsockets_jll.jl/releases/download/4.3.3-bin/libwebsockets.v4.3.3.x86_64-linux-gnu.tar.gz"
