[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "3ba3e49187f068bbb1f552ecd3f365be7bfdcbb6"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "edc552ad2545a16cb66c1834e273398f18fef053f5c5e02fd9a471381e10a436"
    url = "https://gitlab.advsys.work/te/sandbox/libwebsockets_jll.jl/-/package_files/52/download"
